# Generated by Django 4.2.5 on 2023-09-30 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefone',
            name='cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='mail@mail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='idade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='salario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='descricao',
            field=models.CharField(default='Numero de telefone', max_length=30),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='numero',
            field=models.CharField(default='00000000000', max_length=20),
        ),
    ]
