# Generated by Django 4.2.5 on 2023-10-01 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_cpf_cliente_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='departamentos',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='clientes.departamento'),
        ),
    ]
