# Generated by Django 4.2.5 on 2023-10-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_departamento_cliente_departamentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='departamentos',
            field=models.ManyToManyField(blank=True, default=None, to='clientes.departamento'),
        ),
    ]
