# Generated by Django 4.2.5 on 2023-10-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_cliente_foto_alter_cliente_departamentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(upload_to='cliente_fotos'),
        ),
    ]
